services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
      php artisan db:seed --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1up906r433s73f094lg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: api_cursos_2qhk
      - key: DB_USERNAME
        value: laravel_user
      - key: DB_PASSWORD
        value: v17Nmzq9LOIHQOXFpUls89grt7ytHHMD
