services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    startCommand: |
      php artisan config:cache && \
      php artisan migrate --force && \
      php artisan db:seed --force && \
      php artisan storage:link && \
      php artisan l5-swagger:generate && \
      apache2-foreground