services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan storage:link
      php artisan migrate --force
      php artisan db:seed --force
      php artisan l5-swagger:generate
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:3x7hh3sq4SaGeNF9GNbXIrljs0tG9GjBw9d5WfRGRZg=
      - key: APP_DEBUG
        value: false
      - key: L5_SWAGGER_CONST_HOST
        value: https://laravel-app-0zoz.onrender.com/
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1up906r433s73f094lg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: api_cursos_2qhk
      - key: DB_USERNAME
        value: laravel_user
      - key: DB_PASSWORD
        value: v17Nmzq9LOIHQOXFpUls89grt7ytHHMD
